docking_server:
  ros__parameters:
    #Number of times the robot gets to attempt
    retries: 6
    # Distance below which to check abort criteria. should be slightly above docked_distance_threshold (m)
    abort_distance: 0.33
    # Angle offset that triggers abort (radians)
    abort_angle: 0.10
    # Y-offset that triggers abort. (m)
    y_abort_threshold: 0.05
    # The distance to back-off in order to clear the dock connector
    connector_clearance_distance: 0.41
    # Threshold distance that indicates that the robot is docked. (m)
    docked_distance_threshold: 0.31
